### ISSUE TITLE
Setting incorrect timezone causes api to never come online

### ISSUE THREAD

**Issue by OmgImAlexis** [RyanNoelk/OpenEats#60]
If you make a typo or just set the timezone to an incorrect value the API never comes online. Maybe it could default back to another one or show some kind of warning in the UI.

```
ValueError: Incorrect timezone setting: Adelaide/Australia
[2017-01-14 06:00:14 +0000] [13] [INFO] Worker exiting (pid: 13)
Traceback (most recent call last):
  File "/usr/local/bin/gunicorn", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 192, in run
    super(Application, self).run()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 218, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/usr/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 331, in halt
    self.stop()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 381, in stop
    time.sleep(0.1)
  File "/usr/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 231, in handle_chld
    self.reap_workers()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 506, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
```

**Comment by RyanNoelk** [comment]
Weird. Django might have some detection feature for this but I'm not sure exactly how it would work.

**Comment by OmgImAlexis** [comment]
When passing in the timezone you should just pass it to your own function that validates it before setting it. That way if it's invalid you don't just set it and keep the user guessing why nothing will start. A default value is better than a non working product. 😄

**Comment by RyanNoelk** [comment]
Fixed with the above PR ^^
